# .github/workflows/update-readme.yml
name: Update blog list

on:
  workflow_dispatch:      # allows manual runs from the Actions tab or CLI
  schedule:
    - cron: '0 * * * *'   # runs hourly (adjust as needed)

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Update README with latest posts
        run: python3 .github/scripts/update_posts.py

      - name: Commit & push changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          if ! git diff --cached --quiet; then
            git commit -m "chore: update latest blog posts"
            git push
          else
            echo "No changes to commit"
          fi
