name: Update blog list

on:
  schedule:
    - cron: '0 * * * *'    # every hour; adjust if you prefer daily: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: pip install requests

    - name: Update README with latest posts
      run: |
        chmod +x .github/scripts/update_posts.py
        .github/scripts/update_posts.py

    - name: Commit & push changes
      run: |
        git config user.name  "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        # only commit if there are changes
        if ! git diff --cached --quiet; then
          git commit -m "chore: update latest blog posts"
          git push
        else
          echo "No changes to commit"
        fi
